// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608095112_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Core.Domain.Automations.AutomationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapabilityId", "EndpointId");

                    b.HasIndex("RuleId", "Section", "Order");

                    b.ToTable("AutomationActions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompareValuePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "Order");

                    b.HasIndex("DeviceId", "EndpointId", "CapabilityId");

                    b.ToTable("AutomationConditions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedActions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FailureBranchSelected")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingActions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedActions")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulActions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalActions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerCapabilityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TriggerDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerEndpointId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerSource")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerStatePayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("RuleId", "StartedAt");

                    b.ToTable("AutomationExecutions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationExecutionAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AutomationActionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AutomationExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandCorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnresolvedDiffPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CommandCorrelationId");

                    b.HasIndex("AutomationExecutionId", "Section", "Order");

                    b.ToTable("AutomationExecutionActions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionLogic")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CooldownMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastEvaluatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LastEvaluationResult")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastTriggeredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeWindowDaysOfWeekMask")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TimeWindowEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeWindowEndMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeWindowStartMinute")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("HomeId", "Name");

                    b.ToTable("AutomationRules", (string)null);
                });

            modelBuilder.Entity("Core.Domain.DeviceCommands.DeviceCommandExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CorrelationId")
                        .IsUnique();

                    b.HasIndex("DeviceId", "RequestedAt");

                    b.ToTable("DeviceCommandExecutions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.DeviceTelemetry.DeviceCapabilityStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapabilityId", "EndpointId", "ReportedAt");

                    b.ToTable("DeviceCapabilityStateHistories", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionCode")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProvisionedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Uptime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("HomeId");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("ProvisionCode")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Floors.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanvasHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanvasWidth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("HomeId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Homes.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Homes", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("HomeId", "Name");

                    b.ToTable("Scenes", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapabilityId", "EndpointId");

                    b.HasIndex("SceneId", "Section", "Order");

                    b.ToTable("SceneActions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedActions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FailureBranchSelected")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingActions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedActions")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulActions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalActions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerSource")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("SceneId", "StartedAt");

                    b.ToTable("SceneExecutions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecutionAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandCorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneActionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnresolvedDiffPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CommandCorrelationId");

                    b.HasIndex("SceneExecutionId", "Section", "Order");

                    b.ToTable("SceneExecutionActions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationAction", b =>
                {
                    b.HasOne("Core.Domain.Automations.AutomationRule", null)
                        .WithMany("Actions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationCondition", b =>
                {
                    b.HasOne("Core.Domain.Automations.AutomationRule", null)
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationExecutionAction", b =>
                {
                    b.HasOne("Core.Domain.Automations.AutomationExecution", null)
                        .WithMany("Actions")
                        .HasForeignKey("AutomationExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.DeviceCommands.DeviceCommandExecution", b =>
                {
                    b.HasOne("Core.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.DeviceTelemetry.DeviceCapabilityStateHistory", b =>
                {
                    b.HasOne("Core.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Devices.Device", b =>
                {
                    b.OwnsMany("Core.Domain.Devices.DeviceEndpoint", "Endpoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndpointId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceId", "EndpointId")
                                .IsUnique();

                            b1.ToTable("DeviceEndpoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");

                            b1.OwnsMany("Core.Domain.Devices.DeviceCapability", "Capabilities", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CapabilityId")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("CapabilityVersion")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("EndpointId")
                                        .HasColumnType("TEXT");

                                    b2.Property<long>("LastReportedAt")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("SupportedOperations")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("EndpointId", "CapabilityId")
                                        .IsUnique();

                                    b2.ToTable("DeviceCapabilities", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EndpointId");
                                });

                            b1.Navigation("Capabilities");
                        });

                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("Core.Domain.Floors.Floor", b =>
                {
                    b.HasOne("Core.Domain.Homes.Home", null)
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Core.Domain.Floors.FloorRoom", "Rooms", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FillColor")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FloorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("LinkedRoomId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PolygonPayload")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Polygon");

                            b1.HasKey("Id");

                            b1.HasIndex("FloorId");

                            b1.HasIndex("LinkedRoomId");

                            b1.ToTable("FloorRooms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FloorId");
                        });

                    b.OwnsMany("Core.Domain.Floors.PlacedFloorDevice", "PlacedFloorDevices", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FloorId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("FloorRoomId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceId")
                                .IsUnique();

                            b1.HasIndex("FloorId");

                            b1.ToTable("FloorPlacedDevices", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FloorId");
                        });

                    b.Navigation("PlacedFloorDevices");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Core.Domain.Homes.Home", b =>
                {
                    b.OwnsMany("Core.Domain.Homes.Room", "Rooms", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("HomeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("HomeId");

                            b1.ToTable("Rooms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneAction", b =>
                {
                    b.HasOne("Core.Domain.Scenes.Scene", null)
                        .WithMany("Actions")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecutionAction", b =>
                {
                    b.HasOne("Core.Domain.Scenes.SceneExecution", null)
                        .WithMany("Actions")
                        .HasForeignKey("SceneExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationExecution", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Core.Domain.Automations.AutomationRule", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("Core.Domain.Scenes.Scene", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecution", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
