// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624171106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Domain.Models.ActionSets.ActionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionSetType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActionSets", (string)null);

                    b.HasDiscriminator<string>("ActionSetType").HasValue("ActionSet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.ActionSets.ActionSetAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionSetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Payload");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("StatePayload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionSetId", "Section", "Order");

                    b.HasIndex("DeviceId", "CapabilityId", "EndpointId");

                    b.ToTable("ActionSetActions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ActionSets.ActionSetActionExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeviceCommandExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Payload");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("StatePayload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCommandExecutionId")
                        .IsUnique();

                    b.HasIndex("ExecutionId", "Section", "Order");

                    b.ToTable("ActionSetActionExecutions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ActionSets.ActionSetExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActionSetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContinueOnError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionSetId");

                    b.HasIndex("HomeId");

                    b.HasIndex("SourceType", "SourceId", "StartedAt");

                    b.ToTable("ActionSetExecutions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Automations.AutomationCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompareValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("CompareValuePayload");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "Order");

                    b.HasIndex("DeviceId", "EndpointId", "CapabilityId");

                    b.ToTable("AutomationConditions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Automations.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionLogic")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("CooldownMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastEvaluatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("LastEvaluationResult")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastTriggeredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeWindowDaysOfWeekMask")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TimeWindowEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeWindowEndMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeWindowStartMinute")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("HomeId", "Name");

                    b.ToTable("AutomationRules", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Devices.Commands.DeviceCommandExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CorrelationId")
                        .IsUnique();

                    b.HasIndex("DeviceId", "RequestedAt");

                    b.ToTable("DeviceCommandExecutions", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionCode")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProvisionedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Uptime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("HomeId");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("ProvisionCode")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Floors.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanvasHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanvasWidth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("HomeId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Homes.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Homes", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Homes.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Scenes.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("HomeId", "Name");

                    b.ToTable("Scenes", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Automations.AutomationActionSet", b =>
                {
                    b.HasBaseType("Domain.Models.ActionSets.ActionSet");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.HasIndex("RuleId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Automation");
                });

            modelBuilder.Entity("Domain.Models.Scenes.SceneActionSet", b =>
                {
                    b.HasBaseType("Domain.Models.ActionSets.ActionSet");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.HasIndex("SceneId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Scene");
                });

            modelBuilder.Entity("Domain.Models.ActionSets.ActionSetAction", b =>
                {
                    b.HasOne("Domain.Models.ActionSets.ActionSet", null)
                        .WithMany("Actions")
                        .HasForeignKey("ActionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.ActionSets.ActionSetActionExecution", b =>
                {
                    b.HasOne("Domain.Models.Devices.Commands.DeviceCommandExecution", null)
                        .WithMany()
                        .HasForeignKey("DeviceCommandExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.ActionSets.ActionSetExecution", null)
                        .WithMany("Actions")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Automations.AutomationCondition", b =>
                {
                    b.HasOne("Domain.Models.Automations.AutomationRule", null)
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Devices.Commands.DeviceCommandExecution", b =>
                {
                    b.HasOne("Domain.Models.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Devices.Device", b =>
                {
                    b.HasOne("Domain.Models.Homes.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Domain.Models.Devices.DeviceEndpoint", "Endpoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndpointId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceId", "EndpointId")
                                .IsUnique();

                            b1.ToTable("DeviceEndpoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");

                            b1.OwnsMany("Domain.Models.Devices.DeviceCapability", "Capabilities", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CapabilityId")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("CapabilityVersion")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("EndpointId")
                                        .HasColumnType("TEXT");

                                    b2.Property<long>("LastReportedAt")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("SupportedOperations")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("EndpointId", "CapabilityId")
                                        .IsUnique();

                                    b2.ToTable("DeviceCapabilities", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EndpointId");
                                });

                            b1.Navigation("Capabilities");
                        });

                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("Domain.Models.Floors.Floor", b =>
                {
                    b.HasOne("Domain.Models.Homes.Home", null)
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Models.Floors.FloorDevicePlacement", "DevicePlacements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FloorId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceId")
                                .IsUnique();

                            b1.HasIndex("FloorId");

                            b1.ToTable("FloorDevicePlacements", (string)null);

                            b1.HasOne("Domain.Models.Devices.Device", null)
                                .WithOne()
                                .HasForeignKey("Domain.Models.Floors.Floor.DevicePlacements#Domain.Models.Floors.FloorDevicePlacement", "DeviceId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("FloorId");
                        });

                    b.OwnsMany("Domain.Models.Floors.FloorPlanRoom", "FloorPlanRooms", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FillColor")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("FloorId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Polygon")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("FloorId");

                            b1.HasIndex("RoomId")
                                .IsUnique();

                            b1.ToTable("FloorPlanRooms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FloorId");

                            b1.HasOne("Domain.Models.Homes.Room", null)
                                .WithOne()
                                .HasForeignKey("Domain.Models.Floors.Floor.FloorPlanRooms#Domain.Models.Floors.FloorPlanRoom", "RoomId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.Navigation("DevicePlacements");

                    b.Navigation("FloorPlanRooms");
                });

            modelBuilder.Entity("Domain.Models.Homes.Room", b =>
                {
                    b.HasOne("Domain.Models.Homes.Home", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Automations.AutomationActionSet", b =>
                {
                    b.HasOne("Domain.Models.Automations.AutomationRule", null)
                        .WithOne("ActionSet")
                        .HasForeignKey("Domain.Models.Automations.AutomationActionSet", "RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Scenes.SceneActionSet", b =>
                {
                    b.HasOne("Domain.Models.Scenes.Scene", null)
                        .WithOne("ActionSet")
                        .HasForeignKey("Domain.Models.Scenes.SceneActionSet", "SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.ActionSets.ActionSet", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Domain.Models.ActionSets.ActionSetExecution", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Domain.Models.Automations.AutomationRule", b =>
                {
                    b.Navigation("ActionSet")
                        .IsRequired();

                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("Domain.Models.Homes.Home", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Domain.Models.Scenes.Scene", b =>
                {
                    b.Navigation("ActionSet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
