// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Core.Domain.Data.DeviceCapabilityStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReportedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapabilityId", "EndpointId", "ReportedAt");

                    b.ToTable("DeviceCapabilityStateHistories", (string)null);
                });

            modelBuilder.Entity("Core.Domain.DeviceCommandExecutions.DeviceCommandExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CorrelationId")
                        .IsUnique();

                    b.HasIndex("DeviceId", "RequestedAt");

                    b.ToTable("DeviceCommandExecutions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionCode")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProvisionedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Uptime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("HomeId");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("ProvisionCode")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Homes.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Homes", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("HomeId", "Name");

                    b.ToTable("Scenes", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedTargets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FailedTargets");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingTargets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PendingTargets");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedTargets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SkippedTargets");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulTargets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SuccessfulTargets");

                    b.Property<int>("TotalTargets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalTargets");

                    b.Property<string>("TriggerSource")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "StartedAt");

                    b.ToTable("SceneExecutions", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecutionSideEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandCorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamsPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneSideEffectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Timing")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CommandCorrelationId");

                    b.HasIndex("SceneExecutionId", "Order");

                    b.ToTable("SceneExecutionSideEffects", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecutionTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandCorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredStatePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SceneExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneTargetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnresolvedDiffPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CommandCorrelationId");

                    b.HasIndex("SceneExecutionId", "Order");

                    b.ToTable("SceneExecutionTargets", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneSideEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParamsPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Timing")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "Order");

                    b.HasIndex("DeviceId", "CapabilityId", "EndpointId");

                    b.ToTable("SceneSideEffects", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredStatePayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "Order");

                    b.HasIndex("DeviceId", "CapabilityId", "EndpointId");

                    b.ToTable("SceneTargets", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Data.DeviceCapabilityStateHistory", b =>
                {
                    b.HasOne("Core.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.DeviceCommandExecutions.DeviceCommandExecution", b =>
                {
                    b.HasOne("Core.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Devices.Device", b =>
                {
                    b.OwnsMany("Core.Domain.Devices.DeviceEndpoint", "Endpoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EndpointId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("DeviceId", "EndpointId")
                                .IsUnique();

                            b1.ToTable("DeviceEndpoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");

                            b1.OwnsMany("Core.Domain.Devices.DeviceCapability", "Capabilities", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CapabilityId")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("CapabilityVersion")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("EndpointId")
                                        .HasColumnType("TEXT");

                                    b2.Property<long>("LastReportedAt")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("SupportedOperations")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("EndpointId", "CapabilityId")
                                        .IsUnique();

                                    b2.ToTable("DeviceCapabilities", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("EndpointId");
                                });

                            b1.Navigation("Capabilities");
                        });

                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("Core.Domain.Homes.Home", b =>
                {
                    b.OwnsMany("Core.Domain.Homes.Room", "Rooms", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<long>("CreatedAt")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("HomeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("HomeId");

                            b1.ToTable("Rooms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecutionSideEffect", b =>
                {
                    b.HasOne("Core.Domain.Scenes.SceneExecution", null)
                        .WithMany("SideEffects")
                        .HasForeignKey("SceneExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecutionTarget", b =>
                {
                    b.HasOne("Core.Domain.Scenes.SceneExecution", null)
                        .WithMany("Targets")
                        .HasForeignKey("SceneExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneSideEffect", b =>
                {
                    b.HasOne("Core.Domain.Scenes.Scene", null)
                        .WithMany("SideEffects")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneTarget", b =>
                {
                    b.HasOne("Core.Domain.Scenes.Scene", null)
                        .WithMany("Targets")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Domain.Scenes.Scene", b =>
                {
                    b.Navigation("SideEffects");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Core.Domain.Scenes.SceneExecution", b =>
                {
                    b.Navigation("SideEffects");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
